name = "esquie"
main = "src/index.js"
compatibility_date = "2024-06-01"

[assets]
directory = "./src/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"

[env.preview]
name = "esquie-app-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

[env.staging]
name = "esquie-app-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "esquie-app-prod"
routes = [
  { pattern = "esquie.org/*", zone_name = "esquie.org" },
  { pattern = "esquie.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]
[env.production.vars]
ENVIRONMENT = "production"